language: node_js
node_js:
  - 4.1
before_script:
  - npm install -g bower karma
  - bower install
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - sh -e /etc/init.d/xvfb start
script: node_modules/karma/bin/karma start --single-run